Script started on 2022-02-11 14:16:26-05:00 [TERM="xterm-256color" TTY="/dev/pts/5" COLUMNS="80" LINES="24"]
]0;ldc6@gold32: ~[01;32mldc6@gold32[00m:[01;34m~[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (+ 1 2 3 4 5)user=> (+ 1 2 3 4 5)user=> [K(+ 1 2 3 4 5)
15
user=> [Kuser=> [Kuser=> 
[K]0;ldc6@gold32: ~[01;32mldc6@gold32[00m:[01;34m~[00m$ exit

Script done on 2022-02-11 14:21:57-05:00 [COMMAND_EXIT_CODE="0"]
