Script started on 2022-02-11 14:33:52-05:00 [TERM="xterm-256color" TTY="/dev/pts/5" COLUMNS="80" LINES="24"]
]0;ldc6@gold32: ~[01;32mldc6@gold32[00m:[01;34m~[00m$ src   clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (+ 1 2 3 4 5)user=> ([16@print "Welcome to Clojure!")user=> (print[2@ln "Welcome to Clojure!")user=> (print[2P "Welcome to Clojure!")user=> ([16P+ 1 2 3 4 5)user=> [K(fn [x][x] (x + xx)(+ xx)   x)(+ x x))user=> (fn [x] (+ x x))  )user=> (fn [x] (+ x x) )user=> [K(fn [x] (+ x x) )
[K#object[user$eval136$fn__137 0x29182679 "user$eval136$fn__137@29182679"]
user=> [Kuser=> [Kuser=> ((fn [x][x] (x    x +  + xx    x)(+ x x))user=> ((fn [x] (+ x x)) 21)user=> ((fn [x] (+ x x)) 21)  user=> [K((fn [x] (+ x x)) 21)
42
user=> [Kuser=> [Kuser=> ((fn [x y][x y] (+(* x x)(* x x) (* y y)(* y y))(+(* x x) (* y y)))user=> ((fn [x y] (+(* x x) (* y y))) 3 4)user=> ((fn [x y] (+(* x x) (* y y))) 3 4)user=> [K((fn [x y] (+(* x x) (* y y))) 3 4)
25
user=> [Kuser=> [Kuser=> 
[K]0;ldc6@gold32: ~[01;32mldc6@gold32[00m:[01;34m~[00m$ exit

Script done on 2022-02-11 15:02:54-05:00 [COMMAND_EXIT_CODE="0"]
