Script started on 2022-02-11 16:21:29-05:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="80" LINES="24"]
]0;ldc6@gold32: ~[01;32mldc6@gold32[00m:[01;34m~[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> ((fn [x y z][x y z] (+ x y z)(+ x y z))user=> ((fn [x y z] (+ x y z)) 3 4 5)user=> ((fn [x y z] (+ x y z)) 3 4 5)user=> [K((fn [x y z] (+ x y z)) 3 4 5)
[K12
user=> [Kuser=> [Kuser=> ((fn [x][x] (nil? x)(nil? x))user=> ((fn [x] (nil? x)) 6 )user=> ((fn [x] (nil? x)) 6 )user=> [K((fn [x] (nil? x)) 6 )
false
user=> [Kuser=> [Kuser=> ((fn [][] 17.2)user=> ((fn [] 17.2))user=> ((fn [] 17.2))user=> [K((fn [] 17.2))
17.2
user=> [Kuser=> [Kuser=> ((fn [x y z][x y z] (+ x y z)(+ x y z))user=> ((fn [x y z] (+ x y z)) 3 4 5)user=> ((fn [x y z] (+ x y z)) 3 4 5)  8)user=> ((fn [x y z] (+ x y z)) 3 4 8)user=> [K((fn [x y z] (+ x y z)) 3 4 8)
15
user=> [Kuser=> [Kuser=> ((fn [x][x] (nil? x)(nil? x))user=> ((fn [x] (nil? x)) 6 )user=> ((fn [x] (nil? x)) 6 )   nil )user=> ((fn [x] (nil? x)) nil )user=> [K((fn [x] (nil? x)) nil )
true
user=> [Kuser=> [Kuser=> ((fn [][] 17.2)user=> ((fn [] 17.2))user=> ((fn [] 17.2))user=> [K((fn [] 17.2))
17.2
user=> [Kuser=> [Kuser=> 
[K]0;ldc6@gold32: ~[01;32mldc6@gold32[00m:[01;34m~[00m$ exit

Script done on 2022-02-11 16:23:42-05:00 [COMMAND_EXIT_CODE="0"]
