Script started on 2022-02-11 23:21:52-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;ldc6@gold31: ~[01;32mldc6@gold31[00m:[01;34m~[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (defn negate [sequence][sequence]user=> [K[K    (map (fn [n][n][K(defn negate [sequence]
[K    (map (fn [n] (- 0 n )(- 0 n ))    (map (fn [n] (- 0 n )) sequence)    (map (fn [n] (- 0 n )) sequence)[K[K)[K    (map (fn [n] (- 0 n )) sequence)
[K)[K)
[K#'user/negate
user=> [Kuser=> [Kuser=>  (negate [-1 2 -3][-1 2 -3])user=>  (negate [-1 2 -3]) [1P(negate [-1 2 -3])user=> [K(negate [-1 2 -3])
(1 -2 3)
user=> [Kuser=> [Kuser=> (negate [4 -5 6][4 -5 6])user=> (negate [4 -5 6])user=> [K(negate [4 -5 6])
(-4 5 -6)
user=> [Kuser=> [Kuser=> 
[K]0;ldc6@gold31: ~[01;32mldc6@gold31[00m:[01;34m~[00m$ exit

Script done on 2022-02-11 23:24:15-05:00 [COMMAND_EXIT_CODE="0"]
