Script started on 2022-02-12 00:16:25-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;ldc6@gold31: ~[01;32mldc6@gold31[00m:[01;34m~[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (defn sumSquares [sequence][sequence]user=> [K[K   (reduce + (map * sequence sequence)   (reduce + (map * sequence sequence)[K(defn sumSquares [sequence]
[K   (reduce + (map * sequence sequence))   (reduce + (map * sequence sequence)))[K   (reduce + (map * sequence sequence)))
[K#'user/sumSquares
user=> [Kuser=> [Kuser=>  (sumSquares '(1 2 3)(1 2 3))user=> [K (sumSquares '(1 2 3))
14
user=> [Kuser=> [Kuser=>  (sumSquares '(1 2 3 4 5)(1 2 3 4 5))user=> [K (sumSquares '(1 2 3 4 5))
55
user=> [Kuser=> [Kuser=> (sumSquares [-1 -2 -3 0 1][-1 -2 -3 0 1])user=> (sumSquares [-1 -2 -3 0 1])user=> [K(sumSquares [-1 -2 -3 0 1])
15
user=> [Kuser=> [Kuser=> 
[K]0;ldc6@gold31: ~[01;32mldc6@gold31[00m:[01;34m~[00m$ exit

Script done on 2022-02-12 00:18:22-05:00 [COMMAND_EXIT_CODE="0"]
